[server]
port = 8501
address = "localhost"
enableCORS = false
enableXsrfProtection = true

[browser]
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[deprecation]
showfileUploaderEncoding = false

[global]
developmentMode = false
showWarningOnDirectExecution = false

[logger]
level = "error"
messageFormat = "%(message)s"